# Generated by Django 2.1.4 on 2019-01-28 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v4_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sport', models.SmallIntegerField()),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_right_foot', models.BooleanField(default=True)),
                ('post', models.CharField(max_length=30)),
                ('height', models.IntegerField()),
                ('current_number', models.IntegerField(blank=True, null=True)),
                ('overall_power', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(99)])),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v4_team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sport', models.SmallIntegerField()),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('post', models.CharField(max_length=100)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v4_team.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
