# Generated by Django 2.1.4 on 2019-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/players'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/players'),
        ),
    ]
