# Generated by Django 2.1.4 on 2019-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_player', '0002_auto_20190128_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/players'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/players'),
        ),
    ]
