# Generated by Django 2.1.4 on 2019-01-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_player', '0003_auto_20190131_1722'),
        ('v4_player', '0002_auto_20190129_2343'),
    ]

    operations = [
    ]
