# Generated by Django 2.1.4 on 2019-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketballstats',
            name='score_away',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='score_home',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='footballstats',
            name='score_away',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='footballstats',
            name='score_home',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
