# Generated by Django 2.1.4 on 2019-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0003_auto_20190131_2022'),
        ('v4_match', '0002_auto_20190131_1722'),
    ]

    operations = [
    ]
