# Generated by Django 2.1.4 on 2019-01-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0001_initial'),
        ('v4_match', '0004_merge_20190131_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v4_league.League'),
        ),
    ]
