# Generated by Django 2.1.4 on 2019-01-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0005_auto_20190131_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
