# Generated by Django 2.1.4 on 2019-02-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0005_match_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
