# Generated by Django 2.1.4 on 2019-02-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0006_auto_20190131_2249'),
        ('v4_match', '0006_auto_20190201_1106'),
    ]

    operations = [
    ]
