# Generated by Django 2.1.4 on 2019-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0007_merge_20190201_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(null=True),
        ),
    ]
