# Generated by Django 2.1.4 on 2019-02-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0007_merge_20190201_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='minute',
            field=models.IntegerField(),
        ),
    ]
