# Generated by Django 2.1.4 on 2019-02-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0008_auto_20190201_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('گل', 'goal'), ('پاس گل', 'assist'), ('تعویض', 'substitute'), ('کارت قرمز', 'red-card'), ('کارت زرد', 'yellow-card'), ('پرتاب سه امتیازی', '3-points-shot'), ('پرتاب دو امتیازی', 'areal-shot'), ('توپ ربایی', 'steal')], max_length=100),
        ),
    ]
