# Generated by Django 2.1.4 on 2019-02-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0009_auto_20190201_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='resources/images/event-icons')),
                ('event_type', models.CharField(choices=[('گل', 'goal'), ('پاس گل', 'assist'), ('تعویض', 'substitute'), ('کارت قرمز', 'red-card'), ('کارت زرد', 'yellow-card'), ('پرتاب سه امتیازی', '3-points-shot'), ('پرتاب دو امتیازی', 'areal-shot'), ('توپ ربایی', 'steal')], max_length=100)),
            ],
        ),
    ]
