# Generated by Django 2.1.4 on 2019-02-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0012_auto_20190201_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballstats',
            name='possession_away',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='footballstats',
            name='possession_home',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
