# Generated by Django 2.1.4 on 2019-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0015_auto_20190201_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='minute',
            field=models.IntegerField(),
        ),
    ]
