# Generated by Django 2.1.4 on 2019-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0017_auto_20190201_2003'),
        ('v4_match', '0009_auto_20190201_1550'),
    ]

    operations = [
    ]
