# Generated by Django 2.1.4 on 2019-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_match', '0018_merge_20190202_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballstats',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='basketballstats',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='basketballstats',
            name='dribbles',
        ),
        migrations.RemoveField(
            model_name='basketballstats',
            name='steals',
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='penalty_fouls_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='penalty_fouls_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_first_quarter_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_first_quarter_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_fourth_quarter_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_fourth_quarter_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_second_quarter_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_second_quarter_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_third_quarter_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='point_third_quarter_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='rebounds_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='rebounds_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='three_point_shots_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='three_point_shots_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='two_point_shots_away',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='basketballstats',
            name='two_point_shots_home',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
