# Generated by Django 2.1.4 on 2019-01-21 19:55

from django.db import migrations
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('v4_news', '0003_auto_20190121_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now),
        ),
    ]
