# Generated by Django 2.1.4 on 2019-01-31 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_news', '0005_auto_20190129_2336'),
        ('v4_news', '0005_auto_20190128_1910'),
    ]

    operations = [
    ]
