# Generated by Django 2.1.4 on 2019-01-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v4_team', '0004_auto_20190131_2114'),
        ('v4_league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsOfLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField()),
                ('team_difference', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='v4_team.Team'),
        ),
        migrations.AddField(
            model_name='teamsofleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='v4_league.League'),
        ),
        migrations.AddField(
            model_name='teamsofleague',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='v4_team.Team'),
        ),
    ]
