# Generated by Django 2.1.4 on 2019-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0003_remove_league_number_of_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsofleague',
            name='team_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamsofleague',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
    ]
