# Generated by Django 2.1.4 on 2019-02-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0004_auto_20190131_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('name', 'year')},
        ),
    ]
