# Generated by Django 2.1.4 on 2019-02-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0005_auto_20190201_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsofleague',
            name='league',
        ),
        migrations.RemoveField(
            model_name='teamsofleague',
            name='team',
        ),
        migrations.DeleteModel(
            name='TeamsOfLeague',
        ),
    ]
