# Generated by Django 2.1.4 on 2019-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0005_auto_20190201_1118'),
        ('v4_league', '0006_auto_20190201_1925'),
    ]

    operations = [
    ]
