# Generated by Django 2.1.4 on 2019-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_league', '0007_merge_20190202_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
