# Generated by Django 2.1.4 on 2019-01-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v4_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/teams/team_logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='special_pic',
            field=models.ImageField(blank=True, null=True, upload_to='resources/images/teams/special_images'),
        ),
    ]
