# Generated by Django 2.1.4 on 2019-02-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_team', '0004_auto_20190131_2114'),
        ('v4_team', '0004_auto_20190201_0008'),
    ]

    operations = [
    ]
