# Generated by Django 2.1.4 on 2019-02-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v4_team', '0005_merge_20190201_0803'),
        ('v4_team', '0005_merge_20190201_1116'),
    ]

    operations = [
    ]
